services:
  kafka-0:
    restart: always
    image: docker.io/bitnami/kafka
    ports:
      - '9092:9094'
    volumes:
      - 'kafka-volume-0:/bitnami'
    environment:
      - KAFKA_CFG_NODE_ID=0
      # roles which this server can have, later based on a quorum it will be picked as a controller or regular broker
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # servers which take part in a quorum
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      # kafka internal listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # kafka advertised listener, to which clients connects to
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094
      # setting security protocol for each listener
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      # the name used for the listener for the quorum controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # a required cluser id for the KRaft, is expected to contain 16 bytes of a base64-encoded UUID
      - KAFKA_KRAFT_CLUSTER_ID=JRwpSIMelmfcNma0abhl1w
  kafka-1:
    restart: always
    image: docker.io/bitnami/kafka
    ports:
      - '9093:9094'
    volumes:
      - 'kafka-volume-1:/bitnami'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=JRwpSIMelmfcNma0abhl1w
  kafka-2:
    restart: always
    image: docker.io/bitnami/kafka
    ports:
      - '9094:9094'
    volumes:
      - 'kafka-volume-2:/bitnami'
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=JRwpSIMelmfcNma0abhl1w
volumes:
  kafka-volume-0:
  kafka-volume-1:
  kafka-volume-2:
networks:
  kafka-compose_default:
    external: true
